- name: Configure Nginx on EC2 Instances
  hosts: servers
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Deployed by Ansible</h1>"
